### ISSUE TITLE
Podcast challenge dataset

### ISSUE THREAD

**Issue by tdeboissiere** [revdotcom/speech-datasets#18]
Hi !

Would you consider making the audio and transcriptions for the podcast dataset mentioned [in your blogpost](https://www.rev.com/blog/the-podcast-challenge-testing-rev-ais-speech-recognition-accuracy) available in this repository ?

Thanks !

**Comment by qmac** [comment]
Hi Thibault! We still need to work with the podcast creators to get permission to share the raw audios, but this will be the right place to look for them!

**Comment by qmac** [comment]
Uploaded in #50 and #51. See https://github.com/revdotcom/speech-datasets/tree/main/rev16 for details
