### ISSUE TITLE
Releases of the individual datasets?

### ISSUE THREAD

**Issue by jtrmal** [revdotcom/speech-datasets#23]
Hi, I feel like it would be great, if you could prepare also releases of the individual corpora (earnings21, earnings22).
People could then download only the part they care about instead of a zip of whole repo (or getting git of the whole repo).
Just for your consideration  -- but I think you should do it :)

**Comment by nishchalb** [comment]
Hi, does the method in https://github.com/revdotcom/speech-datasets#how-to-check-out-only-a-single-dataset accomplish this for you?
