### ISSUE TITLE
Normalization files for earnings22 dataset

### ISSUE THREAD

**Issue by elchilinga** [revdotcom/speech-datasets#25]
Hi there,

Are there any normalization files for the earnings-22 dataset? If yes, could you please share it with me?

Thanks in advance.

**Comment by elchilinga** [comment]
Hi there,

I want kindly to know, is there any update??

**Comment by pique0822** [comment]
Hi there,
Sorry about the delayed response -- when we released earnings-22 we didn't have plans on releasing the normalized files. If possible, could you share what your use case is, there might be a way we could still help.

**Comment by elchilinga** [comment]
Hi Pique, 

Thanks for the response.

I wanted to change the digits into letters, clear punctuation marks, and also change uppercase into lowercase. If you have a script,  specified especially for the earnings-22 dataset, it would be good.

**Comment by pique0822** [comment]
Hi elchilinga,

Thanks for sharing what you would use the files for, we really appreciate it. From our perspective, it seems like the best path to help you would certainly be sharing the normalization files. It will take us some time however given that we're nearing the end of a quarter and starting up a new one -- we'll give you an update once we have those files ready.

**Comment by AniChilingaryan** [comment]
Hi there, 
Are there any updates on this?

**Comment by qmac** [comment]
Sorry for not getting to this earlier! Added in #45
