### ISSUE TITLE
License for Earnings21 audio

### ISSUE THREAD

**Issue by hbredin** [revdotcom/speech-datasets#43]
License in Earnings21 says:

> The transcripts and associated text files that are used for alignment in this directory are licensed under a [Creative Commons Attribution-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-sa/4.0/) license.

What about the audio files themselves?

**Comment by pique0822** [comment]
Hey @hbredin ! Sorry for the delay in response:

We don't claim ownership over the audio files themselves so we didn't feel that we could apply the license to it. But in the paper, we cite _Swatch Group Management Services Ltd. v. Bloomberg L.P._ as legal precedent that make earnings calls _"fair use"_

**Comment by hbredin** [comment]
So non-commercial, then. Got it! Thanks!
